# Generated by Django 6.0.1 on 2026-02-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'reading'), ('traveling', 'traveling'), ('dancing', 'dancing')], max_length=100)),
                ('studentAddress', models.CharField(max_length=70)),
                ('studentphone', models.CharField(max_length=10)),
                ('studentGender', models.CharField(max_length=10)),
                ('studentDob', models.CharField(max_length=10)),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
    ]
