# Generated by Django 6.0.1 on 2026-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=70)),
                ('personphone', models.IntegerField(max_length=10)),
                ('personAddress', models.CharField(max_length=100)),
                ('personCity', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
