# Generated by Django 6.0.1 on 2026-02-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportNumber', models.IntegerField()),
                ('passportIssuedate', models.DateField()),
                ('passportExpirydate', models.DateField()),
                ('passId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'passport',
            },
        ),
    ]
