# Generated by Django 6.0.1 on 2026-02-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='passId',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='passport',
        ),
    ]
