# Generated by Django 6.0.1 on 2026-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_passport_passid_delete_person_delete_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=10)),
                ('userAddress', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
