# Generated by Django 6.0.1 on 2026-02-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
                ('collegeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.collage')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
